services:
  - type: web
    name: psikoloji-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: REDIS_URL
        fromService:
          type: redis
          name: session-store
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1
      - key: METRICS_PORT
        value: 9090
      - key: FLASK_ENV
        value: production
      - key: WEBSOCKET_PING_INTERVAL
        value: 25
      - key: WEBSOCKET_PING_TIMEOUT
        value: 60
    healthCheckPath: /health
    autoDeploy: true
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1

  - type: redis
    name: session-store
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: noeviction

databases:
  - name: psikoloji-db
    databaseName: psikoloji
    user: psikoloji
    plan: starter
