services:
  - type: web
    name: psikoloji-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --threads 4 wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
    plan: free
