services:
  - type: web
    name: psikoloji-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      gunicorn 
      --worker-class eventlet 
      --workers 1 
      --threads 4 
      --timeout 120 
      --keep-alive 65 
      --log-level debug 
      --access-logfile - 
      --error-logfile - 
      wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: GUNICORN_CMD_ARGS
        value: "--preload --max-requests 1000 --max-requests-jitter 50"
    healthCheckPath: /
    autoDeploy: false
    plan: free
